In [1]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('./Valoración de Perfiles 2D de cerámica ibera-2.csv')

In [4]:
real = [1,5,7,8,9,10,14,15,18,19]
fake = [2,3,4,6,11,12,13,16,17,20]

In [5]:
real_lbl = list(map(lambda x: 'Perfil {}.'.format(x), real))
fake_lbl = list(map(lambda x: 'Perfil {}.'.format(x), fake))

In [6]:
df.columns

Index(['Marca temporal', 'Nombre de usuario', 'Perfil 1.', 'Perfil 2.',
       'Perfil 3.', 'Perfil 4.', 'Perfil 5.', 'Perfil 6.', 'Perfil 7.',
       'Perfil 8.', 'Perfil 9.', 'Perfil 10.', 'Perfil 11.', 'Perfil 12.',
       'Perfil 13.', 'Perfil 14.', 'Perfil 15.', 'Perfil 16.', 'Perfil 17.',
       'Perfil 18.', 'Perfil 19.', 'Perfil 20.'],
      dtype='object')

# REALES

In [7]:
np.array(df[real_lbl])

array([[5, 5, 5, 4, 5, 5, 5, 4, 5, 5],
       [4, 5, 3, 5, 4, 0, 1, 0, 5, 1],
       [3, 5, 5, 2, 5, 4, 4, 3, 5, 4],
       [5, 5, 5, 5, 5, 3, 4, 0, 5, 4],
       [5, 5, 5, 5, 5, 4, 5, 4, 5, 3],
       [0, 5, 4, 3, 4, 3, 4, 2, 5, 3]])

In [8]:
np.mean(np.array(df[real_lbl]), 1)

array([4.8, 2.8, 4. , 4.1, 4.6, 3.3])

In [9]:
np.mean([4.8, 4. , 4.1, 4.6, 3.3])


4.16

In [10]:
np.mean(np.array(df[real_lbl]))

3.933333333333333

In [17]:
np.std(np.array(df[real_lbl]))

1.4590712418826193

# FAKES

In [11]:
np.mean(np.array(df[fake_lbl]), 1)

array([4.9, 2.4, 4.1, 4.3, 4.2, 3.4])

In [12]:
np.mean([4.9, 4.1, 4.3, 4.2, 3.4])

4.18

In [13]:
np.array(df[fake_lbl])

array([[5, 5, 5, 4, 5, 5, 5, 5, 5, 5],
       [0, 4, 3, 0, 4, 4, 4, 4, 0, 1],
       [5, 5, 3, 4, 5, 5, 3, 5, 3, 3],
       [5, 5, 4, 1, 5, 5, 5, 5, 3, 5],
       [5, 1, 5, 3, 5, 5, 5, 5, 3, 5],
       [4, 4, 4, 4, 2, 2, 3, 4, 2, 5]])

In [14]:
np.mean(np.array(df[fake_lbl]))

3.8833333333333333

In [15]:
np.std(np.array(df[fake_lbl]))

1.4386529193041044